---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dlapiduz/c0-worker

inputs:
- name: prometheus-custom-git
- name: prometheus-release-git
- name: version

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

run:
  path: prometheus-custom-git/ci/tasks/create-release.sh

outputs:
- name: pushme
